/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SAinterface.java
 *
 * Created on Apr 1, 2011, 10:23:18 PM
 */

package bitirme.gui;

import bitirme.GmlGraph;
import bitirme.SimulatedAnnealing;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
/**
 *
 * @author munkhuu
 */
public class SAinterface extends javax.swing.JPanel  {
    /** Creates new form SAinterface */
    public SAinterface()  throws FileNotFoundException, IOException  {
        initComponents();
    }
    public static double getInitialTempertur(){
      return SimulatedAnnealing.T;
    }
    public static double getEpsilon(){
      return SimulatedAnnealing.epsilon;
    }
    public static int getFirstLoop(){
      return SimulatedAnnealing.First;
    }
    public static int getSecondLoop(){
      return SimulatedAnnealing.Second;
    }
    public static double getAlpha(){
      return SimulatedAnnealing.alpha;
    }
    public static double getSigma(){
      return SimulatedAnnealing.sigma;
    }
    public static int getClusterNumbers(){
      return SimulatedAnnealing.Cnumber;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        EPSILONbutton = new javax.swing.JTextField();
        EPSILONbutton1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        EPSILONbutton2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        EPSILONbutton3 = new javax.swing.JTextField();
        EPSILONbutton4 = new javax.swing.JTextField();
        EPSILONbutton5 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        EPSILONbutton6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();

        jButton8.setText("open...");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTextField10.setEditable(false);
        jTextField10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField10MouseClicked(evt);
            }
        });
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel30.setText("Source file (*.gml)");

        jButton6.setText("open...");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel11.setText("Temperature :");

        jLabel18.setText("alpha :");

        EPSILONbutton.setText("0.001");
        EPSILONbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EPSILONbuttonActionPerformed(evt);
            }
        });

        EPSILONbutton1.setText("0.95");
        EPSILONbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EPSILONbutton1ActionPerformed(evt);
            }
        });

        jLabel19.setText("alpha(t):");

        EPSILONbutton2.setText("0.05");
        EPSILONbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EPSILONbutton2ActionPerformed(evt);
            }
        });

        jLabel20.setText("In order to stop temperature");

        jLabel21.setText("In order to stop temperature");

        jLabel22.setText("Choosing the step size used in find next fuzzy matrix");

        jLabel23.setText("First loop :");

        jLabel24.setText("Second loop :");

        EPSILONbutton3.setText("6");
        EPSILONbutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EPSILONbutton3ActionPerformed(evt);
            }
        });

        EPSILONbutton4.setText("3");
        EPSILONbutton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EPSILONbutton4ActionPerformed(evt);
            }
        });

        EPSILONbutton5.setText("2");
        EPSILONbutton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EPSILONbutton5ActionPerformed(evt);
            }
        });

        jLabel25.setText("Max number of Clusters :");

        jLabel27.setText("It is outer loop of Simulated Annealing in order to get better result");

        jLabel29.setText("It is inner loop of Simulated Annealing in order to get better result");

        jLabel31.setForeground(java.awt.Color.gray);
        jLabel31.setText(" Please choose file:");

        EPSILONbutton6.setText("400.0");
        EPSILONbutton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EPSILONbutton6ActionPerformed(evt);
            }
        });

        jLabel12.setText("epsilon :");

        jLabel32.setText("Initial temperature");

        jButton9.setText("START");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel33.setText("It won't exceed number of nodes");

        jTextField11.setEditable(false);
        jTextField11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField11MouseClicked(evt);
            }
        });
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jButton7.setText("open...");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel34.setForeground(java.awt.Color.gray);
        jLabel34.setText(" Please enter path of output file:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel23)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel19))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel34)
                                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(EPSILONbutton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(EPSILONbutton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(EPSILONbutton, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(EPSILONbutton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(EPSILONbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EPSILONbutton4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EPSILONbutton3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel32)))
                            .addComponent(jButton7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 1046, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel34)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(EPSILONbutton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EPSILONbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(5, 5, 5)))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EPSILONbutton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton9)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(EPSILONbutton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(EPSILONbutton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(1, 1, 1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EPSILONbutton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EPSILONbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField10MouseClicked

        JFileChooser chooser = new JFileChooser();

        //chooser.setCurrentDirectory(new java.io.File("C:\\Users\\karaa\\Desktop"));
        chooser.setDialogTitle("Please choose file");
        chooser.addChoosableFileFilter(new MyFilter());
        chooser.setAcceptAllFileFilterUsed(true);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            jTextField10.setText(chooser.getSelectedFile().toString());
        } else {
            gmlPath = "";
            jTextField10.setText("File is not choosed!");
        }
}//GEN-LAST:event_jTextField10MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        //gmlFile = new File(jTextField10.getText());
        //gmlPath = gmlFile.getPath();
        
        //System.out.println(gmlPath);
        JFileChooser chooser = new JFileChooser();
        //chooser.setCurrentDirectory(new java.io.File("C:\\Users\\karaa\\Desktop"));
        chooser.setDialogTitle("Please choose file");
        chooser.addChoosableFileFilter(new MyFilter());
        chooser.setAcceptAllFileFilterUsed(true);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            jTextField10.setText(chooser.getSelectedFile().toString());
            gmlPath = jTextField10.getText();
        } else {
            gmlPath = "";
            jTextField10.setText("File is not choosed!");
        }
}//GEN-LAST:event_jButton6ActionPerformed

    private void EPSILONbutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EPSILONbutton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EPSILONbutton3ActionPerformed

    private void EPSILONbutton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EPSILONbutton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EPSILONbutton4ActionPerformed

    private void EPSILONbutton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EPSILONbutton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EPSILONbutton5ActionPerformed

    private void EPSILONbutton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EPSILONbutton6ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_EPSILONbutton6ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(EPSILONbutton6.getText().equals(""))
         SimulatedAnnealing.T = 400.0;
        else {
            SimulatedAnnealing.T = Double.parseDouble(EPSILONbutton6.getText());
        }
        if(EPSILONbutton.getText().equals(""))
         SimulatedAnnealing.epsilon = 0.001;
        else {
            SimulatedAnnealing.epsilon = Double.parseDouble(EPSILONbutton.getText());
        }
        if(EPSILONbutton1.getText().equals(""))
         SimulatedAnnealing.alpha = 0.95;
        else {
            SimulatedAnnealing.alpha = Double.parseDouble(EPSILONbutton1.getText());
        }
        if(EPSILONbutton2.getText().equals(""))
         SimulatedAnnealing.sigma = 0.05;
        else {
            SimulatedAnnealing.sigma = Double.parseDouble(EPSILONbutton2.getText());
        }
        if(EPSILONbutton5.getText().equals(""))
         SimulatedAnnealing.First = 2;
        else {
            SimulatedAnnealing.First = Integer.parseInt(EPSILONbutton5.getText());
        }
        if(EPSILONbutton4.getText().equals(""))
         SimulatedAnnealing.Second = 3;
        else {
            SimulatedAnnealing.Second = Integer.parseInt(EPSILONbutton4.getText());
        }
        if(EPSILONbutton3.getText().equals(""))
         SimulatedAnnealing.Cnumber = 6;
        else {
            SimulatedAnnealing.Cnumber = Integer.parseInt(EPSILONbutton3.getText());
        }
        first = new Thread(new Runnable(){
         public void run() {
                GmlGraph gml = new GmlGraph();
                 try {
                    gml.OpenGmlFile(gmlPath);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(SAinterface.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(SAinterface.class.getName()).log(Level.SEVERE, null, ex);
                }
                SimulatedAnnealing sa = new SimulatedAnnealing();
                sa.T = getInitialTempertur();
                sa.alpha = getAlpha();
                sa.epsilon = getEpsilon();
                sa.First = getFirstLoop();
                sa.Second = getSecondLoop();
                sa.sigma = getSigma();
                sa.Cnumber = getClusterNumbers();              
                try {
                    sa.SA(outPath);
                } catch (IOException ex) {
                    Logger.getLogger(SAinterface.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    gml.CloseGmlFile();
                } catch (IOException ex) {
                    Logger.getLogger(SAinterface.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("End...!!!");
            }
        });
        first.start();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void EPSILONbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EPSILONbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EPSILONbuttonActionPerformed

    private void EPSILONbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EPSILONbutton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EPSILONbutton1ActionPerformed

    private void EPSILONbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EPSILONbutton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EPSILONbutton2ActionPerformed

    private void jTextField11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11MouseClicked

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        //chooser.setCurrentDirectory(new java.io.File("C:\\Users\\karaa\\Desktop\\berkeleydb"));
        chooser.setDialogTitle("Please enter path of output file");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            jTextField11.setText(chooser.getSelectedFile().toString());
            outPath = jTextField11.getText();
            //System.out.println(outPath);
        } else {
            outPath = "";
            jTextField11.setText("Output path is not chosen");

        }
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EPSILONbutton;
    private javax.swing.JTextField EPSILONbutton1;
    private javax.swing.JTextField EPSILONbutton2;
    private javax.swing.JTextField EPSILONbutton3;
    private javax.swing.JTextField EPSILONbutton4;
    private javax.swing.JTextField EPSILONbutton5;
    private javax.swing.JTextField EPSILONbutton6;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    // End of variables declaration//GEN-END:variables
    Thread first;
    File gmlFile;
    String gmlPath = "";
    File outFile;
    String outPath = "";
}
